// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxOwYpICQ0qnbuCW94V4jsRzzx_kcXCVw',
    appId: '1:927273038465:web:52e29e1ca4846290015380',
    messagingSenderId: '927273038465',
    projectId: 'chat-app-e47d6',
    authDomain: 'chat-app-e47d6.firebaseapp.com',
    storageBucket: 'chat-app-e47d6.appspot.com',
    measurementId: 'G-BVGXSS7KPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVJTNAho_7m8bAUCIvdescO7im0tWzOQw',
    appId: '1:927273038465:android:0896eb759960f710015380',
    messagingSenderId: '927273038465',
    projectId: 'chat-app-e47d6',
    storageBucket: 'chat-app-e47d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0roJ0XcsUisYUFUELmhEgkeurlnrKdn8',
    appId: '1:927273038465:ios:93f4ba94b04a04d8015380',
    messagingSenderId: '927273038465',
    projectId: 'chat-app-e47d6',
    storageBucket: 'chat-app-e47d6.appspot.com',
    iosClientId: '927273038465-rvb7l38o6ipoc6jdprkn4vnii7qrsoma.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0roJ0XcsUisYUFUELmhEgkeurlnrKdn8',
    appId: '1:927273038465:ios:93f4ba94b04a04d8015380',
    messagingSenderId: '927273038465',
    projectId: 'chat-app-e47d6',
    storageBucket: 'chat-app-e47d6.appspot.com',
    iosClientId: '927273038465-rvb7l38o6ipoc6jdprkn4vnii7qrsoma.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
